"""Combined dataset output for playlists/channels."""

from __future__ import annotations

import json
import os
import tempfile

from ytx.config import APP_VERSION
from ytx.models import TranscriptResult


def write_combined_jsonl(
    results: list[TranscriptResult],
    output_path: str,
) -> str:
    """Write multiple transcripts as a JSONL file (one JSON object per line)."""
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    tmp_fd, tmp_path = tempfile.mkstemp(
        dir=os.path.dirname(output_path) or ".",
        prefix=".tmp_",
    )
    try:
        with os.fdopen(tmp_fd, "w", encoding="utf-8") as f:
            for result in results:
                if result.transcript is None:
                    continue
                record = {
                    "video_id": result.video.id,
                    "title": result.video.title,
                    "url": result.video.url,
                    "channel_name": result.video.channel.name,
                    "channel_id": result.video.channel.id,
                    "published_at": (
                        result.video.published_at.isoformat()
                        if result.video.published_at else None
                    ),
                    "duration_seconds": result.video.duration_seconds,
                    "language": result.transcript.language,
                    "source": result.transcript.source.value,
                    "segments": [
                        {
                            "start": round(seg.start, 3),
                            "duration": round(seg.duration, 3),
                            "text": seg.text,
                        }
                        for seg in result.transcript.segments
                    ],
                }
                f.write(json.dumps(record, ensure_ascii=False) + "\n")
        os.replace(tmp_path, output_path)
    except BaseException:
        os.unlink(tmp_path)
        raise
    return output_path


def write_combined_markdown(
    results: list[TranscriptResult],
    output_path: str,
) -> str:
    """Write multiple transcripts as a single Markdown file."""
    lines: list[str] = []
    lines.append("# Transcript Collection")
    lines.append("")
    lines.append(f"Videos included: {len(results)}")
    lines.append(f"Generated by YTX v{APP_VERSION}")
    lines.append("")

    for i, result in enumerate(results, 1):
        if result.transcript is None:
            continue
        video = result.video
        lines.append("---")
        lines.append("")
        lines.append(f"## Video {i}: {video.title}")
        lines.append("")
        lines.append(f"- **URL:** {video.url}")
        lines.append(f"- **Channel:** {video.channel.name}")
        if video.published_at:
            lines.append(f"- **Published:** {video.published_at.strftime('%Y-%m-%d')}")
        lines.append(f"- **Language:** {result.transcript.language_name}")
        source_label = result.transcript.source.value.replace("_", " ").title()
        lines.append(f"- **Transcript source:** {source_label}")
        lines.append("")
        lines.append("### Transcript")
        lines.append("")
        for seg in result.transcript.segments:
            lines.append(seg.text)
        lines.append("")

    content = "\n".join(lines)
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    tmp_fd, tmp_path = tempfile.mkstemp(
        dir=os.path.dirname(output_path) or ".",
        prefix=".tmp_",
    )
    try:
        with os.fdopen(tmp_fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(tmp_path, output_path)
    except BaseException:
        os.unlink(tmp_path)
        raise
    return output_path


def write_output_md(
    results: list[TranscriptResult],
    output_path: str,
) -> str:
    """Write output.md: AI-ready combined transcript for flat mode."""
    successful = [r for r in results if r.transcript is not None]
    lines: list[str] = []
    lines.append("# YouTube Transcript Collection")
    lines.append("")
    lines.append(f"Videos: {len(successful)}")
    lines.append("")

    for i, result in enumerate(successful, 1):
        video = result.video
        lines.append(f"## {i}. {video.title}")
        lines.append("")
        lines.append(f"URL: {video.url}")
        lines.append(f"Language: {result.transcript.language_name}")
        source_label = result.transcript.source.value.replace("_", " ").title()
        lines.append(f"Transcript source: {source_label}")
        lines.append("")
        for seg in result.transcript.segments:
            lines.append(seg.text)
        lines.append("")

    content = "\n".join(lines)
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    tmp_fd, tmp_path = tempfile.mkstemp(
        dir=os.path.dirname(output_path) or ".",
        prefix=".tmp_",
    )
    try:
        with os.fdopen(tmp_fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(tmp_path, output_path)
    except BaseException:
        os.unlink(tmp_path)
        raise
    return output_path
